version: '3'
services:
  server:
    image: mksolutions/openvpn:latest
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "$PUBLIC_PORT:1194/$PROTO"
    volumes:
      - /openvpn:/etc/openvpn
